# Generated by Django 5.2.7 on 2026-03-23 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrative', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staff',
            old_name='student_id',
            new_name='user_id',
        ),
    ]
