# Generated by Django 5.2.7 on 2026-03-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modalities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modality',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
