services:
  academia_web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: academia_web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - academia_db

  academia_db:
    image: postgres:15
    container_name: academia_db
    environment:
      POSTGRES_DB: academia
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5438:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
