# Generated by Django 5.2.7 on 2026-03-07 06:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type_document', models.CharField(blank=True, max_length=50, null=True)),
                ('document', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(blank=True, choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], max_length=50, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('foundation_date', models.DateTimeField(blank=True, null=True)),
                ('logo', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True)),
                ('day_of_payment', models.IntegerField()),
                ('next_date_payment', models.DateTimeField(blank=True, null=True)),
                ('last_date_payment', models.DateTimeField(blank=True, null=True)),
                ('status_payment', models.CharField(choices=[('paid', 'Paid'), ('pending', 'Pending'), ('overdue', 'Overdue')], max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
