# Generated by Django 5.2.7 on 2025-10-21 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='members',
        ),
        migrations.RemoveField(
            model_name='company',
            name='modalities',
        ),
        migrations.AddField(
            model_name='modalitie',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modalities', to='gym.company'),
        ),
        migrations.AddField(
            model_name='user',
            name='gym',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gym.company'),
        ),
    ]
