# Generated by Django 5.2.7 on 2025-10-21 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_remove_company_members_remove_company_modalities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modalitie',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modalities', to='gym.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='gym',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='gym.company'),
        ),
    ]
