# Generated by Django 5.2.7 on 2025-10-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_modalitie_gym_alter_user_gym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='last_date_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='next_date_payment',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
