# Generated by Django 5.2.7 on 2025-10-21 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_company_last_date_payment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('personal', 'Personal')], max_length=255, null=True),
        ),
    ]
