# Generated by Django 5.2.7 on 2026-03-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_remove_user_groups_remove_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='day_of_payment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_date_payment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='next_date_payment',
            field=models.DateField(blank=True, null=True),
        ),
    ]
