# Generated by Django 5.2.7 on 2026-03-23 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_user_day_of_payment_user_last_date_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='last_date_payment',
        ),
        migrations.RemoveField(
            model_name='company',
            name='next_date_payment',
        ),
    ]
