# Generated by Django 5.2.7 on 2026-03-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_user_status_payment_user_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('client', 'Client'), ('admin', 'Admin'), ('personal', 'Personal')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20, null=True),
        ),
    ]
